//
// Created by thierry on 2021-04-24.
//

#ifndef ANDROID_SURFACE_VIEW_WITH_VULKAN_VOLK_SETUP_HPP
#define ANDROID_SURFACE_VIEW_WITH_VULKAN_VOLK_SETUP_HPP

#define VK_NO_PROTOTYPES
#define VK_USE_PLATFORM_ANDROID_KHR
#include "../volk/volk.h"

#endif //ANDROID_SURFACE_VIEW_WITH_VULKAN_VOLK_SETUP_HPP
